### ISSUE TITLE
Any chance of resurrection?

### ISSUE THREAD

**Issue by anoduck** [rofl0r/MacGeiger#2]
I noticed the dependency of python2, and immediately hit the proverbial brakes. Honestly, since I discovered it, I thought it was absolutely brilliant. It is just a shame my acknowledgement came years too late. 

Is there any chance of revival?

**Comment by rofl0r** [comment]
you mean the rcb2 build system to build from git ? if you're so allergic to python2, you can just download the latest release tarball that comes with a makefile. it's not much different to git version. rcb2 uses advanced multiprocessing and porting it to py3 is just to much of a hassle because they completely rewrote the multiprocessing part.

**Comment by anoduck** [comment]
> if you're so allergic to python2, you can just download the latest release tarball that comes with a makefile.

No one said anything about being allergic. 🙄 

> rcb2 uses advanced multiprocessing and porting it to py3 is just to much of a hassle because they completely rewrote the multiprocessing part.

Ewww... that does sound quite nasty. All is good, it builds.
